refresh_rate: 10 seconds

root:
  level: info
  appenders:
    - stdout
    - logsFile

appenders:
  stdout:
    kind: console

  logsFile:
    kind: rolling_file
    path: "log/log.log"
    policy:
      kind: compound # 默认值, 即使用所有 policy
      trigger: # 当文件超过10mb 时触发 rotate
        kind: size
        limit: 10mb
      roller: # rotate 类型
        kind: delete # 直接原有文件
        # 或者用 fixed_window
        kind: fixed_window
        pattern: "compressed-log-{}-.log" # 注意, 需要至少包含 "{}" 用于插入索引值
        base: 0 # 压缩日志索引值起点
        count: 10 # 最大保存压缩文件数

loggers:
  app::backend::db:
    level: info

  app::logsFile:
    level: info
    appenders:
      - logsFile
    additive: false